// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Checklist struct {
	ChecklistID pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ChecklistItem struct {
	ChecklistItemID pgtype.UUID
	ChecklistID     pgtype.UUID
	Item            string
	CheckedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type User struct {
	UserID    pgtype.UUID
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
}
