// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT user_id, password FROM users
WHERE username = $1
`

type GetUserRow struct {
	UserID   pgtype.UUID
	Password string
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.UserID, &i.Password)
	return i, err
}

const newUser = `-- name: NewUser :one
insert into users (username, password)
values ($1, $2)
returning user_id
`

type NewUserParams struct {
	Username string
	Password string
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, newUser, arg.Username, arg.Password)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
