// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT username, password FROM users
WHERE username = $1
`

type GetUserRow struct {
	Username string
	Password string
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}

const newUser = `-- name: NewUser :one
insert into users (username, password)
values ($1, $2)
returning username
`

type NewUserParams struct {
	Username string
	Password string
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (string, error) {
	row := q.db.QueryRow(ctx, newUser, arg.Username, arg.Password)
	var username string
	err := row.Scan(&username)
	return username, err
}
